<?php $_product = $block->getProduct(); ?>

<?php
$productInquiryHelper = $this->helper(\PaulSmith\OutOfStockProductInquiry\Helper\Data::class);

$productInquirySku = $_product->getSku();
$productInquiryName = $_product->getName();


?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()) : ?>
    <div class="box-tocart">
        <div class="fieldset">
            <?php if ($block->shouldRenderQuantity()) : ?>
                <div class="field qty">
                    <label class="label" for="qty"><span><?= /* @noEscape */ __('Qty') ?></span></label>
                    <div class="control">
                        <input type="number"
                               name="qty"
                               id="qty"
                               value="<?= /* @noEscape */ $block->getProductDefaultQty() * 1 ?>"
                               title="<?= /* @noEscape */ __('Qty') ?>"
                               class="input-text qty"
                               data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                        />
                    </div>
                </div>
            <?php endif; ?>
            <div class="actions">
                <button type="submit"
                        title="<?= /* @noEscape */ $buttonTitle ?>"
                        class="action primary tocart"
                        id="product-addtocart-button">
                    <span><?= /* @noEscape */ $buttonTitle ?></span>
                </button>
                <?= $block->getChildHtml('', true) ?>
            </div>
        </div>
    </div>
    <script type="text/x-magento-init">
{
    "#product_addtocart_form": {
        "Magento_Catalog/js/validate-product": {}
    }
}
</script>
<?php endif; ?>

<?php
if ($productInquiryHelper->showInquiryLink($_product->getId())) {
    $inquiryTitle = $productInquiryHelper->getOutOfStockProductInquiryTitle();
    ?>

    <div class="inquiry_link_block box-tocart">
        <div class="fieldset">
            <div class="actions">
                <a data-mage-init='{"inquiry_modal": {}}' class="inquiry_link_button primary action" href="JavaScript:void(0);"
                   data-product-inquiry-sku="<?= $block->escapeHtmlAttr($productInquirySku); ?>"
                   >
                    <span><?= $block->escapeHtml($inquiryTitle); ?></span>
                </a>
            </div>
        </div>
    </div>
<?php }?>